const mongoose = require('mongoose');

const cvEvaluationSchema = new mongoose.Schema({
  cv: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'CV',
    required: true,
    index: true // Đánh index để tăng tốc truy vấn
  },
  score: {
    type: Number,
    default: 0,
    min: 0,
    max: 100
  },
  progress: {
    type: Number,
    default: 0,
    min: 0,
    max: 100
  },
  strengths: [String],
  improvements: [String],
  evaluationDate: {
    type: Date,
    default: Date.now
  },
  isAutoGenerated: {
    type: Boolean,
    default: true
  }
}, { timestamps: true });

module.exports = mongoose.model('CVEvaluation', cvEvaluationSchema); 